import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Orbitron } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const orbitron = localFont({
  src: '../public/fonts/Orbitron-VariableFont_wght.ttf', // Adjust path based on your file location
  variable: '--font-orbitron',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${orbitron.variable} ${orbitron.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[##F0F9F5]">{children}</body>
    </html>
  );
}
